### PR TITLE
Support xlink attributes correctly

### LINKED ISSUE #20: xlinkHref not working as expected
As per #11, `<use xlinkHref=#some-icon/>` should render `<use xlink:href="#some-icon"></use>`, but the output is `<use xlinkHref="#some-icon"></use>` and the icon doesn't work as expected. React converts `xlinkHref` to `xlink:href` as expected.

I tried using only `href`, but that doesn't work on mobile Safari on iOS 11.

I'm using `dom-chef: ^3.0.0`.

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #20

### CODE REVIEW

**Comment by filipekiss** [comment]
Hey @bfred-it. thanks for the quick response! Unfortunately, using just `href` is not enough, as Safari still requires `xlink:href`. I did a take on this [here]. Let me know if I should open a PR!

[here]:https://github.com/filipekiss/dom-chef/commit/83fb1cc431b3b0e8ac014775791853d56cf83c68

**Comment by bfred-it** [comment]
Sure you can open a PR, but no need for the `svgDomProperties` map, just generate it on the fly.

**Comment by filipekiss** [comment]
Great! I'll open the PR!

**Comment by bfred-it** [comment]
I tested it in Chrome and Safari (desktop + iOS 11) and `href` works fine:

https://codepen.io/anon/pen/GQweZP

**Comment by bfred-it** [comment]
But React seems to be using `xlink:href` as the attribute name so let's follow that

https://github.com/facebook/react/blob/db47031e635faf17d4ed44dfc72779154d2c86ff/packages/react-dom/src/client/DOMPropertyOperations.js#L155-L169

https://github.com/facebook/react/blob/db47031e635faf17d4ed44dfc72779154d2c86ff/packages/react-dom/src/shared/DOMProperty.js#L460-L466

**Pull request closed without merging**
