### PR TITLE
Convert to Typescript; Export it as ES Module only

### LINKED ISSUE #53: Turn into real ESM module and write in TypeScript
As I suggest in https://github.com/fregante/meta/issues/1, this can be a proper ESM module and we can take the breaking opportunity to also have it output the types (instead of the handwritten d.ts)

### PR DESCRIPTION
**Pull request by fregante**
Closes #53 

This PR is meant as a first-pass, minimal TypeScript conversion avoiding to change browser compatibility (except default parameters being used, at the moment). Further improvements at the expense of compatibility could be discussed and applied later (e.g. `startsWith` instead of `indexOf`)

If you skip the first commit in the Files tab, you'll be able to see the diff on the index.ts file — otherwise git shows the `js` and `ts` as completely different.

_Note:_ dom-chef types are, afaik, ignored if you use JSX. In this case they might just help the code tighter. Technically JSX isn't required though and the current types are incomplete at best.

## Todos

- [x] Setup TypeScript build
- [x] Convert main file
- [x] ~~Convert tests~~
- [x] Double-check compat with Refined GitHub
- [x] Ensure docs are up to date (especially due to ESM)

### CODE REVIEW

**Comment by vadimdemedes** [comment]
Great work! Excited for https://github.com/fregante/meta/issues/1!

**Comment by fregante** [comment]
I have no intention of converting the tests too, it's just too much trouble and I always fail.

I haven't tested it in Refined GitHub yet, but a `next` version has been released.

Hopefully I can do a second pass at this to slightly modernize it (separate PR) before releasing a major version.

**Comment by fregante** [comment]
This appears to work, it'll be tested by everyone in the next GitHub release

**Comment by fregante** [comment]
This should be good to go! ✅

**Comment by jtbandes** [comment]
This looks exciting. You mentioned that types are ignored if using JSX — do you have plans to add types for JSX?

Currently, I have the following in my project. It uses TS's builtin `HTMLElementTagNameMap` and tweaks the types so they work well with dom-chef. I wonder if I might be able to get rid of it some day when dom-chef has full TS type definitions for JSX 🙂 

```ts
type Merge<T, U> = Omit<T, keyof U> & U;

// Since dom-chef doesn't provide type definitions (https://github.com/vadimdemedes/dom-chef/issues/36),
// we can just ask TypeScript to treat JSX elements like actual DOM elements, which is pretty close
// to the actual behavior of dom-chef.
// See: https://www.typescriptlang.org/docs/handbook/jsx.html
declare namespace JSX {
  type JSXChildren = null | undefined | string | Node | JSXChildren[];

  type IntrinsicElements = {
    [K in keyof HTMLElementTagNameMap]: Merge<
      // The HTMLLabelElement API uses 'htmlFor' as the property name for <label> elements,
      // as does React, but with dom-chef we need to use 'for' instead.
      Partial<Omit<HTMLElementTagNameMap[K], "htmlFor">>,
      {
        children?: JSXChildren;
        style?: Partial<HTMLElementTagNameMap[K]["style"]>;
        dangerouslySetInnerHTML?: { __html: string };
      }
    >;
  };
}
```

(and this doesn't support SVG at all btw.)

**Comment by fregante** [comment]
> This looks exciting. You mentioned that types are ignored if using JSX — do you have plans to add types for JSX?

Refer to and discuss on #36 

On Refined GitHub we use:

https://github.com/sindresorhus/refined-github/blob/fc2816f289eba5a8fcee88755969c9171ea718fb/source/globals.d.ts#L38-L51

**Pull request merged**
